# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
# template/.pre-commit-config.yaml
repos:
-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.0
    hooks:
        - id: pip-compile
          args: [requirements.in, -o, requirements.txt]
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.2.1
    hooks:
        - id: commitizen-branch
          stages: [pre-push]
          # This only checks if commits follow the conventional commits format
          # without doing any version bumping

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
          args: [--allow-multiple-documents, --unsafe]  # Add --unsafe to allow duplicate keys
        - id: check-toml
          exclude: ^template/mypy-config\.toml$
        - id: check-added-large-files
        - id: debug-statements
        - id: check-case-conflict
        - id: check-merge-conflict

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.6
    hooks:
        - id: ruff
          args: [--fix]
        - id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
        - id: mypy
          exclude: ^tests/

-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
        - id: codespell
          args: ["--write-changes"]  # Remove this if you prefer to review fixes manually
